version: '3'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: bitnami/nginx:1.25.3
    ports:
      - "80:8081"
      - "443:8443"
    volumes:
      - /opt/services/conf/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - /opt/services/certs:/certs
      - /opt/services/nginx-logs:/opt/bitnami/nginx/logs/
    restart: unless-stopped
    user: "root:root"
    networks:
      - services_net

############################################# Confluence #############################################

  confluence:
    container_name: confluence
    depends_on:
      - postgres-confluence
    image: atlassian/confluence:8.5.2-jdk11
    restart: unless-stopped
    networks:
      - services_net
    volumes:
      - /opt/services/confluence/home-dir:/var/atlassian/application-data/confluence
      #- /opt/services/confluence/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties:/opt/atlassian/confluence/confluence/WEB-INF/classes/log4j.properties
      - /opt/services/certs/cacerts:/opt/java/openjdk/lib/security/cacerts
    environment:
      - 'ATL_JDBC_URL=jdbc:postgresql://postgres-confluence:5432/confluence'
      - 'ATL_JDBC_PASSWORD=tQK8LUeH5CHRzXAC'
      - 'ATL_JDBC_USER=confluenceuser'
      - 'ATL_DB_TYPE=postgresql'
      - 'JVM_MINIMUM_MEMORY=8192m'
      - 'JVM_MAXIMUM_MEMORY=8192m'
      - 'atl_proxy_name=domain_name'
      - 'atl_proxy_port=443'
      - 'atl_tomcat_scheme=https'
      - 'VIRTUAL_HOST=domain_name'
      - 'VIRTUAL_PORT=8090'

  postgres-confluence:
    container_name: postgres-confluence
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - services_net
    volumes:
      - /opt/services/postgres-confluence:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=confluence'
      - 'POSTGRES_USER=confluenceuser'
      - 'POSTGRES_PASSWORD=tQK8LUeH5CHRzXAC'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'

############################################# Confluence #############################################

################################################ Jira ################################################

  jira:
      container_name: jira
      depends_on:
        - postgres-jira
      image: atlassian/jira-software:9.4.5
      restart: unless-stopped
      networks:
        - services_net
      volumes:
        - /opt/services/jiradata:/var/atlassian/application-data/jira
        - /opt/services/certs/cacerts:/opt/java/openjdk/lib/security/cacerts
        #- /opt/services/jiradata/atlassian:/opt/atlassian
      ports:
        - '8080'
      environment:
        - 'ATL_DB_TYPE=postgresql'
        - 'ATL_JDBC_URL=jdbc:postgresql://jira@postgres/jiradb'
        - 'ATL_JDBC_USER=jira'
        - 'ATL_JDBC_PASSWORD=NhZbuLmzEMNVzP7W'
        - 'JVM_MINIMUM_MEMORY=8192m'
        - 'JVM_MAXIMUM_MEMORY=8192m'
        - 'ATL_PROXY_NAME=domain_name'
        - 'ATL_PROXY_PORT=443'
        - 'ATL_TOMCAT_SCHEME=https'
        - 'VIRTUAL_HOST=domain_name'
        - 'VIRTUAL_PORT=8080'
      logging:
        driver: "json-file"
        options:
          max-size: "500k"
          max-file: "50"

  postgres-jira:
    container_name: postgres-jira
    image: postgres:14.7
    restart: unless-stopped
    networks:
      - services_net
    volumes:
      - /opt/services/postgres-jira:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      - 'POSTGRES_PASSWORD=NhZbuLmzEMNVzP7W'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

################################################ Jira ################################################

networks:
  services_net:
    driver: bridge
